<a href="https://colab.research.google.com/github/akbarjon2000/DataScience/blob/main/Drop_indexes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
data = {
    "a":[1,2,3,4,4,5,6],
    "b":[8,7,6,8,9,6,6],
    "c":['s','f','g','r','e','e', 'g']
}

In [6]:
frame = pd.DataFrame(data)

In [7]:
frame

   a  b  c
0  1  8  s
1  2  7  f
2  3  6  g
3  4  8  r
4  4  9  e
5  5  6  e
6  6  6  g

In [8]:
frame.drop(0)

   a  b  c
1  2  7  f
2  3  6  g
3  4  8  r
4  4  9  e
5  5  6  e
6  6  6  g

In [11]:
frame.drop(0, axis = 0)

   a  b  c
1  2  7  f
2  3  6  g
3  4  8  r
4  4  9  e
5  5  6  e
6  6  6  g

In [13]:
frame.drop(0, axis=0, inplace=True)

KeyError: ignored

In [14]:
frame

   a  b  c
1  2  7  f
2  3  6  g
3  4  8  r
4  4  9  e
5  5  6  e
6  6  6  g

In [10]:
frame.drop('a', axis = 1)

   b  c
0  8  s
1  7  f
2  6  g
3  8  r
4  9  e
5  6  e
6  6  g

In [15]:
frame.drop('a', axis=1, inplace=True)

In [17]:
frame

   b  c
1  7  f
2  6  g
3  8  r
4  9  e
5  6  e
6  6  g