<a href="https://colab.research.google.com/github/akbarjon2000/DataScience/blob/main/midterm_exam_Q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Read the CSV file and skip lines with parsing errors
file_path = "/Users/akbarjon/Downloads/waste.xlsx"
df = pd.read_excel(file_path, sheet_name="2017년")
df.head(10)

,i_day,week,i_food_wster_grp,i_food_wst_si,t_pay_type,t_discnt_yn,m_food_wst_cnt,m_food_wst_g,m_food_wst_amt,i_etl_dt,Y,X
0,20170103,화,W6X029,50110,후불,비감면,12,16950,0,2019-07-11 15:34:28,33.489473,126.481764
1,20170103,화,W6X02A,50110,후불,비감면,62,138750,0,2019-07-11 15:34:28,33.476845,126.486417
2,20170103,화,W6X02B,50110,후불,비감면,20,24800,0,2019-07-11 15:34:28,33.491062,126.476087
3,20170103,화,W6X02C,50110,후불,비감면,20,31850,0,2019-07-11 15:34:28,33.487274,126.474518
4,20170103,화,W6X02D,50110,후불,비감면,19,38150,0,2019-07-11 15:34:28,33.487316,126.477164
5,20170103,화,W6X02E,50110,후불,비감면,19,27800,0,2019-07-11 15:34:28,33.488139,126.478150
6,20170103,화,W6X02F,50110,후불,비감면,2,2600,0,2019-07-11 15:34:28,33.486502,126.476995
7,20170103,화,W6X030,50110,후불,비감면,28,62300,0,2019-07-11 15:34:28,33.484446,126.471846
8,20170103,화,W6X031,50110,후불,비감면,51,106050,0,2019-07-11 15:34:28,33.484966,126.471589
9,20170103,화,W6X032,50110,후불,비감면,13,30750,0,2019-07-11 15:34:28,33.485762,126.472522

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Load your dataset (replace 'your_data.csv' with your actual data file)
data = df

# Data Preparation for Waste Amount Prediction
X_amount = data[['m_food_wst_cnt', 'm_food_wst_g']]  # Features affecting Waste Amount
y_amount = data['m_food_wst_amt']  # Target variable (Waste Amount)

# Data Preparation for Waste Count Prediction
X_count = data[['m_food_wst_amt', 'm_food_wst_g']]  # Features affecting Waste Count
y_count = data['m_food_wst_cnt']  # Target variable (Waste Count)

# Split the data into training and test sets for both predictions
X_amount_train, X_amount_test, y_amount_train, y_amount_test = train_test_split(X_amount, y_amount, test_size=0.2, random_state=42)
X_count_train, X_count_test, y_count_train, y_count_test = train_test_split(X_count, y_count, test_size=0.2, random_state=42)

# Waste Amount Prediction using Linear Regression
model_amount = LinearRegression()
model_amount.fit(X_amount_train, y_amount_train)
y_amount_pred = model_amount.predict(X_amount_test)
mse_amount = mean_squared_error(y_amount_test, y_amount_pred)
print(f"Waste Amount Mean Squared Error: {mse_amount}")

# Waste Count Prediction using Random Forest Regression
model_count = RandomForestRegressor(n_estimators=100, random_state=42)
model_count.fit(X_count_train, y_count_train)
y_count_pred = model_count.predict(X_count_test)
mae_count = mean_absolute_error(y_count_test, y_count_pred)
print(f"Waste Count Mean Absolute Error: {mae_count}")

Waste Amount Mean Squared Error: 73471.89097544596
Waste Count Mean Absolute Error: 3.3162615451892683